---
mode: manual
---
# free-kiro-managed:

# CLAUDE.md / .cursorrules / .continuerules — 本项目 AI 编码 agent 指令

本项目使用 **free-kiro** 管理规约工作流。free-kiro 是一个单二进制 CLI，
把代码改动门控在已写好的 spec 文档上。所有改动**先 spec 后代码**。

## free-kiro 在这个项目做什么

- 所有 spec 在 `.kiro/specs/<name>/` 下，包含 `requirements.md` /
  `design.md` / `tasks.md`（或 bugfix 的 `bugfix.md`）。
- spec 阶段流转：draft → requirements → design → tasks → approved →
  implementing → done。
- 阶段流转由 `free-kiro lint` 门控（EARS + 结构规则）。
- tasks.md 里的任务用 `[deps: #N1,#N2]` 声明依赖；
  `free-kiro task list <name>` 显示并行 wave 调度。

## 每个工具调用前（除 Read）

    SPEC=$(cat .kiro/.current 2>/dev/null) && free-kiro spec next "$SPEC"

这是 oracle 的下一步动作建议。如果 lint 失败，先修再继续。
SessionStart hook 会自动跑同样的命令。

如果 `.kiro/.current` 不存在（没活跃 spec），先跑 `free-kiro spec new <name>`，
新 spec 会自动被标记为活跃。

## 编码规范（SessionStart 必须先 Read）

**在写任何 Go 代码之前，先 Read [`docs/CODING_STYLE.md`](../../docs/CODING_STYLE.md)、
[`docs/AGENT_RULES.md`](../../docs/AGENT_RULES.md) 与 [`docs/POLICY.md`](../../docs/POLICY.md)**。

- `docs/CODING_STYLE.md` 仅承载 7 章 Go 社区通用编码规范（命名 / 错误处理 /
  并发 / 接口 / 测试 / 注释 / 依赖）。它是**通用**规范，不是 free-kiro
  专属。
- [`docs/AGENT_RULES.md`](../../docs/AGENT_RULES.md) 承载 AI agent 协作硬性要求
  + 零豁免 / 零死代码政策（违反任意一条 = PR 拒收）。
- [`docs/POLICY.md`](../../docs/POLICY.md) 承载 free-kiro 项目特定策略（覆盖率门槛、
  TODO 注释 owner、协议合规、commit 格式、代码规模上限、PR 范围约束）。

硬约束摘录（来源：[`docs/AGENT_RULES.md`](../../docs/AGENT_RULES.md) §1）：

1. 零 `// TODO` / `// FIXME` / `// XXX` — 未完成的功能**不要写代码**，先
   回 spec 阶段补 requirements/design。
2. 零吞错误（`_ = doX()` / `log.Print(err)` 后继续）。
3. 零硬编码 magic number（端口、超时、阈值都要 `const` 或在 `internal/config`）。
4. 改动 > 50 行先 `free-kiro spec new`，三件套全绿再动代码（**工具特定硬约束**，仅对 free-kiro 仓库有效）。

## 每次 Edit / Write 之前

    free-kiro lint || exit 2

IDE 的 PreToolUse hook 会自动跑。如果看到 lint ERROR，先编辑 spec 文档
（而不是代码），直到 `free-kiro lint` 全绿，再继续。

## 完成实现时

    free-kiro spec complete <name>

## 帮助

- `free-kiro --help` — 命令树
- `free-kiro doctor` — 诊断安装 + hook 问题
- `docs/EARS.md` — EARS 句式参考
- `docs/HOOKS.md` — hook 配置参考
- `docs/STEERING.md` — 项目上下文注入规则

<!-- free-kiro-managed:start -->

<!-- auto-generated by free-kiro steering inject; do not edit -->

## product.md

# Product

`free-kiro` 是一个**规约式开发工作流引擎**。它是 AWS Kiro IDE 核心
spec-driven 工作流的免费、跨平台、单二进制克隆版。

## 一句话定位

> 把"先想清楚 → 再动手"做成**强约束门禁**：agent 必须先把需求/设计/
> 任务写成 spec 文档、过 lint，才能写代码。

## 目标用户

使用 Claude Code / CodeBuddy / Cursor / Continue 等 AI coding 工具的
开发者。痛点是：agent 一上手就开始改文件，可能性空间迅速发散，复杂
任务经常失控。

## 核心能力（v0.8.0）

| 能力 | 说明 |
|---|---|
| spec 状态机 | `draft → requirements → design → tasks → approved → implementing → done` |
| EARS lint | 5 种 EARS 句式 + 无条件基线，缺漏即拦截 |
| bugfix 三段式 | Current / Expected / Unchanged Behavior 契约 |
| tasks wave | `tasks.md` 依赖图 → 拓扑排序 → 并行 wave 调度 |
| steering 两级作用域 | workspace 覆盖 global，4 种 inclusion 模式 |
| hook 信封 | 写出的 JSON 兼容 Kiro IDE event-keyed 格式 |
| drift 检测 | approve 时锁 baseline，编辑后自动暴露差异 |
| advisory | vague / 重复 AC / 可追溯性问题（不阻塞） |
| 可视化 CLI | ASCII tree + Mermaid |
| 可视化 Web | 本地 dashboard，fsnotify 实时推送 + ETag/304 缓存 |
| Dashboard UI | spec 详情面板（hash deep-link + deps 链接 + sparkline + a11y）+ 4 widget + E2E |
| 跨多 spec | `.kiro/.current` 自动标记活跃 spec |
| issue→spec | `free-kiro spec new --from-issue <gh-url>` |
| PRD→spec | `--from-prd <url>` / `--from-browser <url>` |
| 实时 watch | `free-kiro watch --preset reactive` |
| 自升级 | `free-kiro upgrade` 校验 SHA256 + re-exec |
| demo 流程 | `top1-demo-onboarding` spec 提供首次跑通的端到端示例 |

## 安装与分发

- Homebrew tap：`brew install jingyu525/tap/free-kiro`
- `curl|bash` 一行脚本（自动检测平台 + 写 `~/.local/bin`）
- GitHub Releases 直下（GoReleaser 跨 6 个平台）

## 非目标（防止 scope creep）

- **不是** Kiro IDE 的复刻 —— 不做 IDE、不做云端协作、不做账号体系
- **不替代** lint 工具 —— 只做 spec 文档的结构与语义门禁
- **不引入** 与 spec 工作流无关的新外部依赖 —— 保持 Go stdlib + 3 个直接依赖的精简哲学
- **不绑定** 单一 AI coding 工具 —— 通过 hook 信封兼容所有支持 hook 的工具

## structure.md

# Structure

## 顶层布局

```
free-kiro/
├── cmd/free-kiro/            # main 入口（Cobra root 命令）
├── internal/                 # 全部业务逻辑（私有包）
│   ├── cli/                  # Cobra 子命令注册与 flag 绑定
│   ├── ide/                  # IDE hook 信封生成（Claude Code / CodeBuddy）
│   │   └── templates/        # IDE hook 配置文件模板
│   ├── lint/                 # EARS + 结构 + 依赖图 lint 引擎
│   ├── spec/                 # spec 文档读写 + 状态机推进 + drift 检测
│   │   ├── templates/        # spec 文档生成模板
│   │   ├── analyze.go        # requirement/design 静态分析
│   │   ├── drift.go          # baseline 锁与差异检测
│   │   └── warn.go           # advisory（vague / 重复 AC / 可追溯性）
│   ├── steering/             # steering 注入与作用域解析
│   ├── taskgraph/            # tasks.md 依赖图 → wave 拓扑
│   ├── hooks/                # hook JSON 信封序列化
│   ├── watch/                # fsnotify 文件监听
│   ├── workspace/            # .kiro/ 目录发现与对账
│   ├── models/               # 跨包共享的数据结构（spec/hook/steering）
│   ├── visualize/            # ASCII tree / Mermaid / web dashboard
│   │   ├── server.go         # http.Server + 路由
│   │   ├── server_handlers.go# HTML 渲染 + REST API
│   │   ├── server_sse.go     # fsnotify → SSE 实时推送
│   │   ├── etag.go           # ETag 生成 + 304 缓存协商
│   │   ├── io.go             # 文件 IO 适配层
│   │   ├── middleware.go     # HTTP 中间件
│   │   └── static/           # web dashboard 前端静态资源
│   ├── skill/                # self-install 的 skill bundle 读写
│   ├── upgrade/              # 自升级下载 + SHA256 校验
│   ├── frontmatter/          # YAML frontmatter 解析（spec/steering 共用）
│   ├── text/                 # 文本处理工具（normalize / dedent 等）
│   └── errors/               # 包级 sentinel 错误 + wrap helper
├── docs/                     # 面向用户的文档
├── contrib/                  # 第三方分发物料（Homebrew formula、skill bundle）
├── testdata/                 # 测试 fixture
├── install.sh                # curl|bash 安装脚本
├── .goreleaser.yaml          # 跨平台构建配置
├── .golangci.yml             # golangci-lint v2 配置（启用 staticcheck / errcheck / revive）
├── go.mod / go.sum
└── README.md
```

## 包约定

- **包名**：小写单词，不复数，不缩写（`spec` 而非 `specs`，`lint` 而非 `l`）
- **导出符号**：每个 exported 类型/函数/常量必须有 godoc 注释
- **IO 隔离**：所有外部 IO（文件、网络、子进程）必须放在显式 adapter 后，
  便于测试时 mock
- **依赖方向**：`cli → models + 各领域包`，领域包之间禁止互相 import
  内部细节（只允许通过 `models` 共享类型）
- **错误处理**：跨包错误用 sentinel（在 `internal/errors`）+ `fmt.Errorf %w`
  wrap；不要把 string repr 当 error identity
- **测试**：单元测试与被测文件同包同目录（`*_test.go`），不开 mirror package

## 模板与生成器分离

- `*/templates/*.md.tmpl` 只放模板字符串
- 生成器是纯函数（输入结构 → 输出字符串），不做 IO
- 模板里不嵌入业务逻辑，逻辑全部前置到生成器

## dashboard 后端拆分约定

`internal/visualize/` 把 dashboard 服务拆成多个职责单一的文件：

- `server.go`：路由注册 + 生命周期
- `server_handlers.go`：HTML 渲染 + REST handler
- `server_sse.go`：SSE 长连接 + fsnotify 订阅
- `etag.go`：缓存协商逻辑（与 handler 解耦，便于单测）
- `io.go`：文件系统读取
- `middleware.go`：logging / CORS / recovery

新增 dashboard 端点时，先确认要落在哪个文件；横向功能（如指标采集）开新
文件，不要往 `server_handlers.go` 里堆。

<!-- free-kiro-managed:end -->

