---
mode: manual
---
# free-kiro-managed:

# CLAUDE.md / .cursorrules / .continuerules — 本项目 AI 编码 agent 指令

本项目使用 **free-kiro** 管理规约工作流。free-kiro 是一个单二进制 CLI，
把代码改动门控在已写好的 spec 文档上。所有改动**先 spec 后代码**。

## free-kiro 在这个项目做什么

- 所有 spec 在 `.kiro/specs/<name>/` 下，包含 `requirements.md` /
  `design.md` / `tasks.md`（或 bugfix 的 `bugfix.md`）。
- spec 阶段流转：draft → requirements → design → tasks → approved →
  implementing → done。
- 阶段流转由 `free-kiro lint` 门控（EARS + 结构规则）。
- tasks.md 里的任务用 `[deps: #N1,#N2]` 声明依赖；
  `free-kiro task list <name>` 显示并行 wave 调度。

## 每个工具调用前（除 Read）

    SPEC=$(cat .kiro/.current 2>/dev/null) && free-kiro spec next "$SPEC"

这是 oracle 的下一步动作建议。如果 lint 失败，先修再继续。
SessionStart hook 会自动跑同样的命令。

如果 `.kiro/.current` 不存在（没活跃 spec），先跑 `free-kiro spec new <name>`，
新 spec 会自动被标记为活跃。

## 项目上下文（自动注入的 steering）

本文件末尾由 `<!-- free-kiro-managed:start -->` /

<!-- auto-generated by free-kiro steering inject; do not edit -->

## product.md

# Product

`free-kiro` 是一个**规约式开发工作流引擎**。它是 AWS Kiro IDE 核心
spec-driven 工作流的免费、跨平台、单二进制克隆版。

## 一句话定位

> 把"先想清楚 → 再动手"做成**强约束门禁**：agent 必须先把需求/设计/
> 任务写成 spec 文档、过 lint，才能写代码。

## 目标用户

使用 Claude Code / CodeBuddy / Cursor / Continue 等 AI coding 工具的
开发者。痛点是：agent 一上手就开始改文件，可能性空间迅速发散，复杂
任务经常失控。

## 核心能力（v0.8.0）

| 能力 | 说明 |
|---|---|
| spec 状态机 | 主流路径为线性 `draft → requirements → design → tasks → approved → implementing → done`；planning 阶段（requirements / design / tasks）可互转；APPROVED → TASKS 是合法回填；完整合法迁移表见 `internal/models/phase.go` 的 `allowed` 切片 |
| EARS lint | 5 种 EARS 触发句式（when / while / where / unless / if-then）+ 1 个 ubiquitous 基线，共 6 类正则分支（`internal/lint/ears.go` 的 `EARSRe` 含 6 个 alternation），缺漏即拦截 |
| bugfix 三段式 | Current / Expected / Unchanged Behavior 契约，附 `defect-uses-shall` 反向规则（缺陷绝不能 SHALL 化） |
| tasks wave | `tasks.md` 依赖图 → 拓扑排序 → 并行 wave 调度 |
| steering 两级作用域 | workspace 覆盖 global，4 种 inclusion 模式（always / auto / manual / filematch） |
| hook 信封 | 写出的 JSON 兼容 Kiro IDE event-keyed 格式 |
| drift 检测 | approve 时锁 baseline，编辑后自动暴露差异 |
| advisory | 4 类 finding 代码：`vague-language` / `duplicate-acceptance-criteria` / `uncovered-acceptance-criteria` / `tasks-without-requirements`（不阻塞；详见 `internal/spec/analyze.go:53-115`） |
| 可视化 CLI | ASCII tree + Mermaid |
| 可视化 Web | 本地 dashboard，fsnotify 实时推送 + ETag/304 缓存；fsnotify 在容器 / 网络 FS 不可用时降级为 2s mtime 轮询（`internal/visualize/server_sse.go` `watchChangesFallback`），端到端延迟可达 2s+ |
| Dashboard UI | spec 详情面板（hash deep-link + deps 链接 + sparkline + a11y）+ 4 个核心 widget（`stat-card` / `sparkline-cell` / `phase-badge` / `waves-progress`）+ E2E；另有 9 个辅助 widget 见 `internal/visualize/static/src/widgets/` |
| 跨多 spec | `.kiro/.current` 自动标记活跃 spec |
| issue→spec | `free-kiro spec new --from-issue <gh-url>`；前置依赖 `gh` CLI（`brew install gh` + `gh auth login`） |
| PRD→spec | `--from-prd <url>`（仅需网络可达）/ `--from-browser <url>`（前置依赖 `bsk` CLI + browser-skill + Chromium 登录态） |
| 实时 watch | `free-kiro watch --preset <name>`，5 个 preset：`default` / `lint` / `status` / `reactive`（=lint+status）/ `full`（=lint+status+report） |
| 自升级 | `free-kiro upgrade` 校验 SHA256 + re-exec；POSIX (Linux/macOS) 路径 `os.Exec` 替换当前进程；Windows 下不自动 re-exec，升级后需手动重跑 `free-kiro upgrade` 或重启进程 |
| demo 流程 | `top1-demo-onboarding` spec 提供首次跑通的端到端示例 |

## 安装与分发

- Homebrew tap：`brew install jingyu525/tap/free-kiro`
- `curl|bash` 一行脚本（自动检测平台 + 写 `~/.local/bin`）
- GitHub Releases 直下（GoReleaser 跨 6 个平台）

## 非目标（防止 scope creep）

- **不是** Kiro IDE 的复刻 —— 不做 IDE、不做云端协作、不做账号体系
- **不替代** lint 工具 —— 只做 spec 文档的结构与语义门禁
- **不引入** 与 spec 工作流无关的新外部依赖 —— 保持 Go stdlib + 3 个直接依赖的精简哲学
- **不绑定** 单一 AI coding 工具 —— 通过 hook 信封兼容所有支持 hook 的工具

## structure.md

# Structure

## 顶层布局

```
free-kiro/
├── AGENTS.md / CLAUDE.md  # 注入到 Claude Code / Cursor 的项目级指令
├── CONTRIBUTING.md        # 贡献流程
├── LICENSE                # 开源协议
├── Makefile               # 常用开发命令（build / test / lint / verify）
├── README.md
├── cmd/free-kiro/            # main 入口（Cobra root 命令）
├── docs/                     # 面向用户的文档
├── examples/                 # 示例 fixture（如 todo-app）
├── testdata/                 # 测试 fixture（含 bsk-stub / inject 子目录）
├── install.sh                # curl|bash 安装脚本
├── contrib/                  # 第三方分发物料（当前仅 skill bundle 子目录；Homebrew formula 改由 release.yml 推送）
├── .goreleaser.yaml          # 跨平台构建配置（5 平台，见 tech.md）
├── .golangci.yml             # golangci-lint v2 配置（启用 staticcheck / errcheck / revive）
├── go.mod / go.sum
└── internal/                 # 全部业务逻辑（私有包）
```

## internal/ 顶层包

| 包 | 职责 | 代表性文件 |
|---|---|---|
| `cli/` | Cobra 子命令注册与 flag 绑定 | ~22 个 cobra 命令文件（每个子命令一文件：spec*、init、lint、watch、upgrade、serve、doctor、demo、skill*、status、hook、task 等）；完整命令清单见 `cmd/free-kiro/main.go` 的 `rootCmd.AddCommand(...)` 注册 |
| `ide/` | IDE hook 信封生成（Claude Code / CodeBuddy 等） | `init.go`、`templates/`（实际是 `agents_*.md` / `instructions_*.md` 模板，不是 `.tmpl`） |
| `lint/` | EARS + 结构 + 依赖图 lint 引擎 | `ears.go`（EARS 正则）/ `bugfix.go`（三段式）/ `requirements.go` & `tasks.go`（结构 lint）/ `linter.go`（总入口）/ `baseline.go`（基线规则）/ `quality.go`（质量指标 / semantic gates） |
| `spec/` | spec 文档读写 + 状态机推进 + drift 检测 | `engine.go` / `engine_io.go` / `engine_state.go`（状态机）/ `generator.go`（生成器）/ `analyze.go`（advisory）/ `drift.go`（baseline 锁）/ `warn.go`（vague / 重复 AC / 追溯）/ `templates/`（4 个 .tmpl） |
| `steering/` | steering 注入与作用域解析 | `frontmatter.go` / `assemble.go`（4 种 inclusion 模式选择）/ `store.go`（两级作用域） |
| `taskgraph/` | tasks.md 依赖图 → wave 拓扑 | `waves.go`（拓扑排序 + 并行 wave）/ `cycle.go`（DetectCycle） |
| `hooks/` | hook JSON 信封序列化 | `envelope.go`（Kiro 兼容 event-keyed）/ `dispatch.go` / `registry.go` / `glob.go` |
| `watch/` | fsnotify 文件监听 | `watcher.go`（fallback 2s mtime 轮询） |
| `workspace/` | `.kiro/` 目录发现与对账 | `workspace.go`（含 `.current` 标记） |
| `models/` | 跨包共享的数据结构 | `spec.go` / `hook.go` / `phase.go` / `task.go` / `steering.go` |
| `visualize/` | ASCII tree / Mermaid / web dashboard | `server.go`（路由 + 生命周期）/ `server_handlers.go`（HTML 渲染 + REST）/ `server_sse.go`（SSE + fsnotify）/ `etag.go`（缓存协商）/ `io.go`（文件 IO 适配）/ `middleware.go`（logging / CORS / recovery）/ `mermaid.go`（Mermaid LR 渲染）/ `report.go` / `visualize.go` / `static/`（前端） |
| `visualize/static/` | **完整的 Vite + FSD 前端工程** | `index.html`（embed.FS 入口）/ `vite.config.ts` / `package.json` / `pnpm-lock.yaml` / `src/`（FSD: app/ entities/ features/ pages/ shared/ widgets/）/ `dist/`（build 产物）/ `scripts/`（check-fsd-layers.mjs、e2e-dashboard.mjs）/ `node_modules/` |
| `skill/` | self-install 的 skill bundle 读写 | `app.go` / `install.go` / `manifest.go` / `paths.go` / `release.go` / `show.go`（与 `contrib/skills/` 无软链 / 拷贝关系，独立脚本化分发） |
| `upgrade/` | 自升级下载 + SHA256 校验 | `upgrade.go`（Check/Apply/reexec；POSIX `os.Exec`，Windows 不 re-exec）/ `io.go` |
| `frontmatter/` | YAML frontmatter 解析（spec/steering 共用） | `frontmatter.go` / `schema.go` |
| `text/` | 文本处理工具（normalize / dedent 等） | `text.go` |
| `errors/` | 包级 sentinel 错误 + wrap helper | `errors.go` |

## 包约定

- **包名**：小写单词，不复数，不缩写（`spec` 而非 `specs`，`lint` 而非 `l`）
- **导出符号**：每个 exported 类型/函数/常量必须有 godoc 注释
- **IO 隔离**：所有外部 IO（文件、网络、子进程）必须放在显式 adapter 后，
  便于测试时 mock
- **依赖方向**：`cli → models + 各领域包`，领域包之间禁止互相 import
  内部细节（只允许通过 `models` 共享类型）
- **错误处理**：跨包错误用 sentinel（在 `internal/errors`）+ `fmt.Errorf %w`
  wrap；不要把 string repr 当 error identity
- **测试**：单元测试与被测文件同包同目录（`*_test.go`），不开 mirror package

## 模板与生成器分离

- `*/templates/*.md.tmpl` 只放模板字符串
- 生成器是纯函数（输入结构 → 输出字符串），不做 IO
- 模板里不嵌入业务逻辑，逻辑全部前置到生成器

## dashboard 后端拆分约定

`internal/visualize/` 把 dashboard 服务拆成多个职责单一的文件：

- `server.go`：路由注册 + 生命周期
- `server_handlers.go`：HTML 渲染 + REST handler
- `server_sse.go`：SSE 长连接 + fsnotify 订阅
- `etag.go`：缓存协商逻辑（与 handler 解耦，便于单测）
- `io.go`：文件系统读取
- `middleware.go`：logging / CORS / recovery

新增 dashboard 端点时，先确认要落在哪个文件；横向功能（如指标采集）开新
文件，不要往 `server_handlers.go` 里堆。

## 文档漂移修正说明

本节记录 structure.md 与实际仓库**已确认**的差异，避免未来误读：

- **`contrib/` 当前不含 Homebrew formula**：Homebrew 分发改由 `.github/workflows/release.yml` 推送（避开 GoReleaser v2 的 brews 段已知 bug），不再落在 `contrib/` 下
- **`internal/skill/` 与 `contrib/skills/` 无软链 / 拷贝关系**：skill bundle 是独立脚本化分发（`contrib/skills/scripts/`），源码与 bundle 是两套产物
- **`ide/templates/` 实际是 `agents_*.md` / `instructions_*.md` 模板**：不是 `.tmpl` 文件，是 IDE 指令文件直接复制粘贴的目标

`<!-- free-kiro-managed:end -->` marker 包裹的 markdown 块，由
`free-kiro steering inject` 在每次 `init` / `inject` 运行时自动生成，
内容来自 `.kiro/steering/*.md` 中 `mode: always` 的文档（当前为
`product.md` / `structure.md` / `tech.md`）。

**这段内容不是用户手写的**——它是项目级 steering store 的 always 模式
快照。若要修改，请编辑 `.kiro/steering/<name>.md` 后跑
`free-kiro steering inject`（或 `free-kiro init --ide auto
--overwrite-instructions`）同步到这里。详见 `docs/STEERING.md`
§"自动注入到 IDE 指令文件"。

## 编码规范（SessionStart 必须先 Read）

**在写任何 Go 代码之前，先 Read [`docs/CODING_STYLE.md`](../../docs/CODING_STYLE.md)、
[`docs/AGENT_RULES.md`](../../docs/AGENT_RULES.md) 与 [`docs/POLICY.md`](../../docs/POLICY.md)**。

- `docs/CODING_STYLE.md` 仅承载 7 章 Go 社区通用编码规范（命名 / 错误处理 /
  并发 / 接口 / 测试 / 注释 / 依赖）。它是**通用**规范，不是 free-kiro
  专属。
- [`docs/AGENT_RULES.md`](../../docs/AGENT_RULES.md) 承载 AI agent 协作硬性要求
  + 零豁免 / 零死代码政策（违反任意一条 = PR 拒收）。
- [`docs/POLICY.md`](../../docs/POLICY.md) 承载 free-kiro 项目特定策略（覆盖率门槛、
  TODO 注释 owner、协议合规、commit 格式、代码规模上限、PR 范围约束）。

硬约束摘录（来源：[`docs/AGENT_RULES.md`](../../docs/AGENT_RULES.md) §1）：

1. 零 `// TODO` / `// FIXME` / `// XXX` — 未完成的功能**不要写代码**，先
   回 spec 阶段补 requirements/design。
2. 零吞错误（`_ = doX()` / `log.Print(err)` 后继续）。
3. 零硬编码 magic number（端口、超时、阈值都要 `const` 或在 `internal/config`）。
4. 改动 > 50 行先 `free-kiro spec new`，三件套全绿再动代码（**工具特定硬约束**，仅对 free-kiro 仓库有效）。

## 每次 Edit / Write 之前

    free-kiro lint || exit 2

IDE 的 PreToolUse hook 会自动跑。如果看到 lint ERROR，先编辑 spec 文档
（而不是代码），直到 `free-kiro lint` 全绿，再继续。

## 完成实现时

    free-kiro spec complete <name>

## 帮助

- `free-kiro --help` — 命令树
- `free-kiro doctor` — 诊断安装 + hook 问题
- `docs/EARS.md` — EARS 句式参考
- `docs/HOOKS.md` — hook 配置参考
- `docs/STEERING.md` — 项目上下文注入规则

<!-- free-kiro-managed:start -->

<!-- auto-generated by free-kiro steering inject; do not edit -->

## product.md

# Product

`free-kiro` 是一个**规约式开发工作流引擎**。它是 AWS Kiro IDE 核心
spec-driven 工作流的免费、跨平台、单二进制克隆版。

## 一句话定位

> 把"先想清楚 → 再动手"做成**强约束门禁**：agent 必须先把需求/设计/
> 任务写成 spec 文档、过 lint，才能写代码。

## 目标用户

使用 Claude Code / CodeBuddy / Cursor / Continue 等 AI coding 工具的
开发者。痛点是：agent 一上手就开始改文件，可能性空间迅速发散，复杂
任务经常失控。

## 核心能力（v0.8.0）

| 能力 | 说明 |
|---|---|
| spec 状态机 | 主流路径为线性 `draft → requirements → design → tasks → approved → implementing → done`；planning 阶段（requirements / design / tasks）可互转；APPROVED → TASKS 是合法回填；完整合法迁移表见 `internal/models/phase.go` 的 `allowed` 切片 |
| EARS lint | 5 种 EARS 触发句式（when / while / where / unless / if-then）+ 1 个 ubiquitous 基线，共 6 类正则分支（`internal/lint/ears.go` 的 `EARSRe` 含 6 个 alternation），缺漏即拦截 |
| bugfix 三段式 | Current / Expected / Unchanged Behavior 契约，附 `defect-uses-shall` 反向规则（缺陷绝不能 SHALL 化） |
| tasks wave | `tasks.md` 依赖图 → 拓扑排序 → 并行 wave 调度 |
| steering 两级作用域 | workspace 覆盖 global，4 种 inclusion 模式（always / auto / manual / filematch） |
| hook 信封 | 写出的 JSON 兼容 Kiro IDE event-keyed 格式 |
| drift 检测 | approve 时锁 baseline，编辑后自动暴露差异 |
| advisory | 4 类 finding 代码：`vague-language` / `duplicate-acceptance-criteria` / `uncovered-acceptance-criteria` / `tasks-without-requirements`（不阻塞；详见 `internal/spec/analyze.go:53-115`） |
| 可视化 CLI | ASCII tree + Mermaid |
| 可视化 Web | 本地 dashboard，fsnotify 实时推送 + ETag/304 缓存；fsnotify 在容器 / 网络 FS 不可用时降级为 2s mtime 轮询（`internal/visualize/server_sse.go` `watchChangesFallback`），端到端延迟可达 2s+ |
| Dashboard UI | spec 详情面板（hash deep-link + deps 链接 + sparkline + a11y）+ 4 个核心 widget（`stat-card` / `sparkline-cell` / `phase-badge` / `waves-progress`）+ E2E；另有 9 个辅助 widget 见 `internal/visualize/static/src/widgets/` |
| 跨多 spec | `.kiro/.current` 自动标记活跃 spec |
| issue→spec | `free-kiro spec new --from-issue <gh-url>`；前置依赖 `gh` CLI（`brew install gh` + `gh auth login`） |
| PRD→spec | `--from-prd <url>`（仅需网络可达）/ `--from-browser <url>`（前置依赖 `bsk` CLI + browser-skill + Chromium 登录态） |
| 实时 watch | `free-kiro watch --preset <name>`，5 个 preset：`default` / `lint` / `status` / `reactive`（=lint+status）/ `full`（=lint+status+report） |
| 自升级 | `free-kiro upgrade` 校验 SHA256 + re-exec；POSIX (Linux/macOS) 路径 `os.Exec` 替换当前进程；Windows 下不自动 re-exec，升级后需手动重跑 `free-kiro upgrade` 或重启进程 |
| demo 流程 | `top1-demo-onboarding` spec 提供首次跑通的端到端示例 |

## 安装与分发

- Homebrew tap：`brew install jingyu525/tap/free-kiro`
- `curl|bash` 一行脚本（自动检测平台 + 写 `~/.local/bin`）
- GitHub Releases 直下（GoReleaser 跨 6 个平台）

## 非目标（防止 scope creep）

- **不是** Kiro IDE 的复刻 —— 不做 IDE、不做云端协作、不做账号体系
- **不替代** lint 工具 —— 只做 spec 文档的结构与语义门禁
- **不引入** 与 spec 工作流无关的新外部依赖 —— 保持 Go stdlib + 3 个直接依赖的精简哲学
- **不绑定** 单一 AI coding 工具 —— 通过 hook 信封兼容所有支持 hook 的工具

## structure.md

# Structure

## 顶层布局

```
free-kiro/
├── AGENTS.md / CLAUDE.md  # 注入到 Claude Code / Cursor 的项目级指令
├── CONTRIBUTING.md        # 贡献流程
├── LICENSE                # 开源协议
├── Makefile               # 常用开发命令（build / test / lint / verify）
├── README.md
├── cmd/free-kiro/            # main 入口（Cobra root 命令）
├── docs/                     # 面向用户的文档
├── examples/                 # 示例 fixture（如 todo-app）
├── testdata/                 # 测试 fixture（含 bsk-stub / inject 子目录）
├── install.sh                # curl|bash 安装脚本
├── contrib/                  # 第三方分发物料（当前仅 skill bundle 子目录；Homebrew formula 改由 release.yml 推送）
├── .goreleaser.yaml          # 跨平台构建配置（5 平台，见 tech.md）
├── .golangci.yml             # golangci-lint v2 配置（启用 staticcheck / errcheck / revive）
├── go.mod / go.sum
└── internal/                 # 全部业务逻辑（私有包）
```

## internal/ 顶层包

| 包 | 职责 | 代表性文件 |
|---|---|---|
| `cli/` | Cobra 子命令注册与 flag 绑定 | ~22 个 cobra 命令文件（每个子命令一文件：spec*、init、lint、watch、upgrade、serve、doctor、demo、skill*、status、hook、task 等）；完整命令清单见 `cmd/free-kiro/main.go` 的 `rootCmd.AddCommand(...)` 注册 |
| `ide/` | IDE hook 信封生成（Claude Code / CodeBuddy 等） | `init.go`、`templates/`（实际是 `agents_*.md` / `instructions_*.md` 模板，不是 `.tmpl`） |
| `lint/` | EARS + 结构 + 依赖图 lint 引擎 | `ears.go`（EARS 正则）/ `bugfix.go`（三段式）/ `requirements.go` & `tasks.go`（结构 lint）/ `linter.go`（总入口）/ `baseline.go`（基线规则）/ `quality.go`（质量指标 / semantic gates） |
| `spec/` | spec 文档读写 + 状态机推进 + drift 检测 | `engine.go` / `engine_io.go` / `engine_state.go`（状态机）/ `generator.go`（生成器）/ `analyze.go`（advisory）/ `drift.go`（baseline 锁）/ `warn.go`（vague / 重复 AC / 追溯）/ `templates/`（4 个 .tmpl） |
| `steering/` | steering 注入与作用域解析 | `frontmatter.go` / `assemble.go`（4 种 inclusion 模式选择）/ `store.go`（两级作用域） |
| `taskgraph/` | tasks.md 依赖图 → wave 拓扑 | `waves.go`（拓扑排序 + 并行 wave）/ `cycle.go`（DetectCycle） |
| `hooks/` | hook JSON 信封序列化 | `envelope.go`（Kiro 兼容 event-keyed）/ `dispatch.go` / `registry.go` / `glob.go` |
| `watch/` | fsnotify 文件监听 | `watcher.go`（fallback 2s mtime 轮询） |
| `workspace/` | `.kiro/` 目录发现与对账 | `workspace.go`（含 `.current` 标记） |
| `models/` | 跨包共享的数据结构 | `spec.go` / `hook.go` / `phase.go` / `task.go` / `steering.go` |
| `visualize/` | ASCII tree / Mermaid / web dashboard | `server.go`（路由 + 生命周期）/ `server_handlers.go`（HTML 渲染 + REST）/ `server_sse.go`（SSE + fsnotify）/ `etag.go`（缓存协商）/ `io.go`（文件 IO 适配）/ `middleware.go`（logging / CORS / recovery）/ `mermaid.go`（Mermaid LR 渲染）/ `report.go` / `visualize.go` / `static/`（前端） |
| `visualize/static/` | **完整的 Vite + FSD 前端工程** | `index.html`（embed.FS 入口）/ `vite.config.ts` / `package.json` / `pnpm-lock.yaml` / `src/`（FSD: app/ entities/ features/ pages/ shared/ widgets/）/ `dist/`（build 产物）/ `scripts/`（check-fsd-layers.mjs、e2e-dashboard.mjs）/ `node_modules/` |
| `skill/` | self-install 的 skill bundle 读写 | `app.go` / `install.go` / `manifest.go` / `paths.go` / `release.go` / `show.go`（与 `contrib/skills/` 无软链 / 拷贝关系，独立脚本化分发） |
| `upgrade/` | 自升级下载 + SHA256 校验 | `upgrade.go`（Check/Apply/reexec；POSIX `os.Exec`，Windows 不 re-exec）/ `io.go` |
| `frontmatter/` | YAML frontmatter 解析（spec/steering 共用） | `frontmatter.go` / `schema.go` |
| `text/` | 文本处理工具（normalize / dedent 等） | `text.go` |
| `errors/` | 包级 sentinel 错误 + wrap helper | `errors.go` |

## 包约定

- **包名**：小写单词，不复数，不缩写（`spec` 而非 `specs`，`lint` 而非 `l`）
- **导出符号**：每个 exported 类型/函数/常量必须有 godoc 注释
- **IO 隔离**：所有外部 IO（文件、网络、子进程）必须放在显式 adapter 后，
  便于测试时 mock
- **依赖方向**：`cli → models + 各领域包`，领域包之间禁止互相 import
  内部细节（只允许通过 `models` 共享类型）
- **错误处理**：跨包错误用 sentinel（在 `internal/errors`）+ `fmt.Errorf %w`
  wrap；不要把 string repr 当 error identity
- **测试**：单元测试与被测文件同包同目录（`*_test.go`），不开 mirror package

## 模板与生成器分离

- `*/templates/*.md.tmpl` 只放模板字符串
- 生成器是纯函数（输入结构 → 输出字符串），不做 IO
- 模板里不嵌入业务逻辑，逻辑全部前置到生成器

## dashboard 后端拆分约定

`internal/visualize/` 把 dashboard 服务拆成多个职责单一的文件：

- `server.go`：路由注册 + 生命周期
- `server_handlers.go`：HTML 渲染 + REST handler
- `server_sse.go`：SSE 长连接 + fsnotify 订阅
- `etag.go`：缓存协商逻辑（与 handler 解耦，便于单测）
- `io.go`：文件系统读取
- `middleware.go`：logging / CORS / recovery

新增 dashboard 端点时，先确认要落在哪个文件；横向功能（如指标采集）开新
文件，不要往 `server_handlers.go` 里堆。

## 文档漂移修正说明

本节记录 structure.md 与实际仓库**已确认**的差异，避免未来误读：

- **`contrib/` 当前不含 Homebrew formula**：Homebrew 分发改由 `.github/workflows/release.yml` 推送（避开 GoReleaser v2 的 brews 段已知 bug），不再落在 `contrib/` 下
- **`internal/skill/` 与 `contrib/skills/` 无软链 / 拷贝关系**：skill bundle 是独立脚本化分发（`contrib/skills/scripts/`），源码与 bundle 是两套产物
- **`ide/templates/` 实际是 `agents_*.md` / `instructions_*.md` 模板**：不是 `.tmpl` 文件，是 IDE 指令文件直接复制粘贴的目标

<!-- free-kiro-managed:end -->
