package cli

import (
	"bytes"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/jingyu525/free-kiro/internal/steering"
)

// TestSteeringInject_RunInject_SkippedDoesNotAffectExitCode verifies the
// behavior pinned by spec `fix-steering-inject-skipped-exit`: when one
// or more target files are skipped (e.g. .continue/rules/... missing),
// runInject emits a stderr warning per skipped file but returns
// normally (no os.Exit), so cmd.Execute() reports a nil error and
// callers see exit code 0.
//
// We construct the InjectResult directly rather than going through
// Store.InjectAll so the test stays focused on runInject's exit-code
// semantics without depending on the steering-package fixture.
func TestSteeringInject_RunInject_SkippedDoesNotAffectExitCode(t *testing.T) {
	res := &steering.InjectResult{
		Block: "<!-- auto-generated by free-kiro steering inject; do not edit -->\n\n## product.md\nbody",
		Written: []string{
			"CLAUDE.md",
			"AGENTS.md",
			".cursorrules",
			".cursor/rules/free-kiro.md",
		},
		Skipped: []steering.InjectSkip{
			{Path: ".continue/rules/free-kiro.md", Reason: "missing inject marker, run free-kiro init first"},
		},
		DocCount: 1,
	}

	// Build a synthetic cobra command so runInject has cmd.OutOrStdErr
	// to write into. We invoke runInject directly to avoid spinning
	// up the full CLI parsing path.
	cmd := &cobra.Command{Use: "inject"}
	var stdout, stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)

	// runInject does not call os.Exit when Skipped is non-empty after
	// the fix; the call below returns normally, which is what we
	// assert by simply reaching the line after.
	runInject(cmd, res, false)

	out := stdout.String()
	errOut := stderr.String()

	// 4 written lines go to stdout.
	if got := strings.Count(out, "✓ wrote "); got != 4 {
		t.Errorf("stdout wrote count = %d, want 4; got:\n%s", got, out)
	}
	// 1 skipped warning goes to stderr with the expected shape.
	if !strings.Contains(errOut, "warning: file .continue/rules/free-kiro.md: missing inject marker") {
		t.Errorf("stderr missing skipped warning; got:\n%s", errOut)
	}
	if got := strings.Count(errOut, "warning: file "); got != 1 {
		t.Errorf("stderr warning count = %d, want 1; got:\n%s", got, errOut)
	}
}

// TestSteeringInject_RunInject_NoSkippedExitsZero is a control test
// covering the happy path: when every target is written successfully
// and none is skipped, runInject returns cleanly with empty stderr.
func TestSteeringInject_RunInject_NoSkippedExitsZero(t *testing.T) {
	res := &steering.InjectResult{
		Block:  "<!-- auto-generated by free-kiro steering inject; do not edit -->\n\n## tech.md\nbody",
		Written: []string{"CLAUDE.md", "AGENTS.md"},
		Skipped: nil,
		DocCount: 1,
	}
	cmd := &cobra.Command{Use: "inject"}
	var stdout, stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)

	runInject(cmd, res, false)

	if got := strings.Count(stdout.String(), "✓ wrote "); got != 2 {
		t.Errorf("stdout wrote count = %d, want 2", got)
	}
	if stderr.Len() != 0 {
		t.Errorf("stderr should be empty when no skipped; got %q", stderr.String())
	}
}

// TestSteeringInject_RunInject_DryRunSkippedGuard ensures --dry-run
// short-circuits before the skipped loop, so callers using dry-run
// never observe a "warning: file ..." line on stderr.
func TestSteeringInject_RunInject_DryRunSkippedGuard(t *testing.T) {
	res := &steering.InjectResult{
		Block:   "## product.md\nbody",
		Written: nil,
		Skipped: []steering.InjectSkip{{Path: "x", Reason: "y"}},
		DocCount: 1,
	}
	cmd := &cobra.Command{Use: "inject"}
	var stdout, stderr bytes.Buffer
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)

	runInject(cmd, res, true)

	// In dry-run, Block is printed and Skipped is ignored.
	if !strings.Contains(stdout.String(), "## product.md") {
		t.Errorf("dry-run should print Block to stdout; got %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Errorf("dry-run should suppress skipped warnings; got %q", stderr.String())
	}
}

// TestSteeringInject_ExitCodeConstants pins the public exit-code
// contract pinned by spec `fix-steering-inject-skipped-exit`:
//
//	injectExitOK      = 0   (all reachable targets processed; skipped are warnings)
//	injectExitNoDocs  = 3   (no always-mode steering docs in .kiro/steering/)
//	injectExitBadGlob = 4   (--only glob syntax invalid)
//
// `injectExitMaxSkipped` was REMOVED by this fix — its existence would
// re-introduce the drift between spec and pre-commit hook.
func TestSteeringInject_ExitCodeConstants(t *testing.T) {
	if injectExitOK != 0 {
		t.Errorf("injectExitOK = %d, want 0", injectExitOK)
	}
	if injectExitNoDocs != 3 {
		t.Errorf("injectExitNoDocs = %d, want 3", injectExitNoDocs)
	}
	if injectExitBadGlob != 4 {
		t.Errorf("injectExitBadGlob = %d, want 4", injectExitBadGlob)
	}
}
