package steering

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jingyu525/free-kiro/internal/models"
)

// Inject-marker constants used by both `internal/steering/inject.go`
// (the writer) and `internal/ide/templates/instructions_*.md` /
// `agents_*.md` (the templates). Keep these literal strings in sync —
// tests assert the templates embed the same markers.
const (
	InjectMarkerStart = "<!-- free-kiro-managed:start -->"
	InjectMarkerEnd   = "<!-- free-kiro-managed:end -->"
	// InjectBlockHeader is the first line written inside the marker
	// region, signaling to human readers that the block was
	// machine-generated and should not be edited by hand.
	InjectBlockHeader = "<!-- auto-generated by free-kiro steering inject; do not edit -->"
)

// DefaultInjectTargets lists the 5 IDE project-root instruction files
// that `free-kiro steering inject` writes by default. The list mirrors
// docs/HOOKS.md §"每只写哪里（v0.8.0+）":
//
//	Claude Code → CLAUDE.md
//	OpenCode / CodeBuddy → AGENTS.md (single shared file)
//	Cursor legacy → .cursorrules
//	Cursor modular → .cursor/rules/free-kiro.md
//	Continue modular → .continue/rules/free-kiro.md
//
// Continue's legacy .continuerules is intentionally excluded: it is
// auto-loaded only when the user opts in to Continue's legacy loader,
// and the modular path covers the common case.
var DefaultInjectTargets = []string{
	"CLAUDE.md",
	"AGENTS.md",
	".cursorrules",
	".cursor/rules/free-kiro.md",
	".continue/rules/free-kiro.md",
}

// InjectResult summarizes one InjectAll call.
//
// InjectAll NEVER returns an error; per-file failures become Skipped
// entries so the CLI layer can decide the exit code (0 / 3 / 4 /
// skipped-count, see docs/STEERING.md and the steering-inject spec).
type InjectResult struct {
	// Block is the assembled markdown that was (or would be) injected
	// between the marker region. Empty when no always-mode docs exist.
	Block string
	// Written holds relative paths of target files successfully
	// updated. Empty in --dry-run mode.
	Written []string
	// Skipped holds targets that were not written, with a human-readable
	// reason (missing marker / IO error / glob mismatch).
	Skipped []InjectSkip
	// DocCount is the number of always-mode docs that were (or would
	// be) included in Block. Drives exit-code 3 (no docs).
	DocCount int
}

// InjectSkip describes one target file that was skipped during inject.
type InjectSkip struct {
	Path   string
	Reason string
}

// InjectAll assembles always-mode steering docs into a markdown block
// and writes the block into the marker region of each target
// instruction file. onlyGlob filters the target paths via filepath.Match
// semantics (supports `*` and `?`, no `**`). Empty onlyGlob means "all
// targets".
//
// The function never returns an error. Callers inspect InjectResult:
//   - DocCount == 0 → exit 3 (no always docs to inject)
//   - len(Skipped) > 0 → exit = min(len(Skipped), 5)
//   - else → exit 0
func (s *Store) InjectAll(onlyGlob string) InjectResult {
	docs := s.alwaysDocsSorted()
	res := InjectResult{
		Block:    assembleBlock(docs),
		DocCount: len(docs),
	}
	targets := filterTargets(DefaultInjectTargets, onlyGlob)
	for _, rel := range targets {
		abs := filepath.Join(s.ws.Root(), rel)
		written, skip := injectToFile(abs, rel, res.Block)
		if written {
			res.Written = append(res.Written, rel)
		}
		if skip != nil {
			res.Skipped = append(res.Skipped, *skip)
		}
	}
	return res
}

// alwaysDocsSorted returns LoadAll() filtered to mode=always, sorted
// by doc Name (alphabetical). Empty when no always docs exist.
func (s *Store) alwaysDocsSorted() []models.SteeringDoc {
	var out []models.SteeringDoc
	for _, d := range s.LoadAll() {
		if d.Mode == "always" {
			out = append(out, d)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// assembleBlock renders the always-mode docs into a single markdown
// block. The block is meant to live between InjectMarkerStart and
// InjectMarkerEnd in target files:
//
//	<!-- free-kiro-managed:start -->
//	<!-- auto-generated by free-kiro steering inject; do not edit -->
//
//	## product.md
//	<product body>
//
//	## structure.md
//	<structure body>
//	<!-- free-kiro-managed:end -->
//
// Returns an empty string when docs is empty.
func assembleBlock(docs []models.SteeringDoc) string {
	if len(docs) == 0 {
		return ""
	}
	var sb strings.Builder
	sb.WriteString(InjectBlockHeader)
	for _, d := range docs {
		sb.WriteString("\n\n")
		fmt.Fprintf(&sb, "## %s.md\n", d.Name)
		body := strings.TrimRight(d.Content, "\n")
		sb.WriteString(body)
	}
	return sb.String()
}

// filterTargets keeps only the targets whose basename matches onlyGlob.
// Empty onlyGlob passes everything through. filepath.Match uses shell
// glob syntax (* and ? only; ** is not supported by design — see spec
// AC-4).
func filterTargets(targets []string, onlyGlob string) []string {
	if onlyGlob == "" {
		return targets
	}
	out := make([]string, 0, len(targets))
	for _, t := range targets {
		base := filepath.Base(t)
		if matched, _ := filepath.Match(onlyGlob, base); matched {
			out = append(out, t)
		}
	}
	return out
}

// indexLineContaining returns the 0-based line index of the first line
// in content that contains substr (substring match, no regex). Returns
// -1 when substr is not found.
func indexLineContaining(content, substr string) int {
	for i, line := range strings.Split(content, "\n") {
		if strings.Contains(line, substr) {
			return i
		}
	}
	return -1
}

// injectToFile reads absPath, locates the InjectMarkerStart /
// InjectMarkerEnd pair, replaces the content BETWEEN the two marker
// lines with block, and writes the result back. The marker lines
// themselves are preserved verbatim.
//
// Returns (true, nil) on success, (false, &InjectSkip{...}) on failure
// (missing marker, IO error). The marker lines are located by line
// substring match — they may appear anywhere on a line.
func injectToFile(absPath, relPath, block string) (bool, *InjectSkip) {
	data, err := os.ReadFile(absPath)
	if err != nil {
		return false, &InjectSkip{Path: relPath, Reason: err.Error()}
	}
	content := string(data)
	lines := strings.Split(content, "\n")

	startIdx := -1
	endIdx := -1
	for i, line := range lines {
		switch {
		case startIdx == -1 && strings.Contains(line, InjectMarkerStart):
			startIdx = i
		case startIdx != -1 && endIdx == -1 && strings.Contains(line, InjectMarkerEnd):
			endIdx = i
		}
		if endIdx != -1 {
			break
		}
	}
	if startIdx == -1 || endIdx == -1 || endIdx <= startIdx {
		return false, &InjectSkip{Path: relPath, Reason: "missing inject marker, run free-kiro init first"}
	}

	prefix := strings.Join(lines[:startIdx+1], "\n")
	suffix := strings.Join(lines[endIdx:], "\n")
	prefix = strings.TrimRight(prefix, "\n")
	suffix = strings.TrimLeft(suffix, "\n")
	blockContent := strings.TrimRight(block, "\n")

	newContent := prefix + "\n\n" + blockContent + "\n\n" + suffix
	if err := os.WriteFile(absPath, []byte(newContent), 0o644); err != nil {
		return false, &InjectSkip{Path: relPath, Reason: err.Error()}
	}
	return true, nil
}
